apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskweb
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
        tier: web
    spec:
      containers:
      - name: flask
        image: bmets/kanoe
        env:
        - name: APP_SETTINGS
          value: config.DevelopmentConfig
        - name: DATABASE_URL
          value: postgresql://localhost/kanoe
        ports:
        - containerPort: 5000
